### PR TITLE
2018-12-04 Meeting Notes

### PR DESCRIPTION
**Pull request by jlaura**
Thanks to @rfergason for taking these.

### CODE REVIEW

**Comment by jessemapel** [comment]
@jlaura Can we get a PDF of your slides added somewhere?

**Comment by jlaura** [comment]
:+1: I need to figure out where to host that, but yes. Maybe I'll just PR that into the repo. Any major downside there if the file will be static anyway?

**Comment by rbeyer** [comment]
Seems like GitHub might not be the best thing for all of these pieces.  A shared folder on Google drive would allow us to make changes more interactively as we work.

**Comment by jlaura** [comment]
I agree google drive would be the natural place. Unfortunately, our gov. google stuff is locked down to inside the agency.... 

Ross - do you want to create a drive folder that we can use? I am happy to upload the deck and any assorted documents such as those.

**Comment by jlaura** [comment]
@jessemapel I just pushed these into the shared google drive as a pdf. Not sure how to get the actual deck pushed into the drive natively, but the pdf is a record of the presentation along with the notes in this PR.

**Pull request merged**
