### PR TITLE
Set next meeting time - Dec 18 @12PM

### PR DESCRIPTION
**Pull request by jlaura**

### CODE REVIEW

**Comment by rbeyer** [comment]
10 AM Mountain, 9 AM Pacific: I have a 1-time conflict that morning from 8:45 to 10:45 AM PST.  In general, Tuesday mornings are okay, but I may have to miss this one.

**Comment by jlaura** [comment]
How about we push to 11? I just picked this time out of a hat.

**Comment by rbeyer** [comment]
If noon for you works, then 11 AM PST (noon MST) works for me.

**Comment by rbeyer** [comment]
Also, the Hangout audio todqy kept loosing packets, so it was hard to hear sometimes.

**Comment by jlaura** [comment]
PR is updated. I'll get a Zoom room setup and we will be in a different room here that does not seem to have those audio issues.

**Comment by jlaura** [comment]
@all I am going to merge, if people have agenda items, but open a PR and add them.

**Pull request merged**
