### PR TITLE
Tweaked TSC membership change wording

### PR DESCRIPTION
**Pull request by jessemapel**
This is a (late) follow up from the February TSC meeting. The TSC voted to modify the proposed change from #19 to how membership change voting works.

At the meeting the votes were as follows:

In favor: Jesse, Summer, Ross, Jay
Not present: Michael

@michaelaye Can you weigh in on this and vote through this PR?

### CODE REVIEW

**Comment by michaelaye** [comment]
Was the implication of the name change discussed at the last meeting? Do the “in favors” imply being in favor of that name change? ;)

**Comment by rbeyer** [comment]
Ah, no.  There are two things in that PR, the name change and the how-we-vote-to-accept-new-members.  We should split those out into separate PRs, because we didn't talk about the name change at all.

**Comment by jessemapel** [comment]
We didn't talk about the name change. I'll add that to the agenda for *gasp* next week. This is purely how we vote to change membership. I think we should ask @rfergason to modify her PR after that.

**Comment by jessemapel** [comment]
@michaelaye Do you have further questions about this? I'd like to get this closed off.

**Comment by michaelaye** [comment]
No further questions, sorry for the delay!

**Pull request merged**
